FROM nvidia/cuda:12.1.0-cudnn8-runtime-ubuntu22.04

RUN apt update && apt install -y \
        python3.11 \
        python3-pip \
        curl \
        wget \
        git \
        git-lfs \
        dcm2niix && \
    apt clean

RUN rm /usr/bin/python3 && \
    ln -s /usr/bin/python3.11 /usr/bin/python3 && \
    ln -s /usr/bin/python3.11 /usr/bin/python

RUN python3 -m pip install --upgrade pip
COPY requirements.txt /env/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /env/requirements.txt

COPY entrypoint.sh /env/entrypoint.sh
RUN chmod +x /env/entrypoint.sh

ENTRYPOINT [ "/env/entrypoint.sh" ]
